### ISSUE TITLE
XML namespace issue 

### ISSUE THREAD

**Issue by stefanponik** [cmprescott/ansible-xml#102]
Hi, 

I have encounter issue with parser for XML when there is XML namespace while using xpath. 

Removing namespace fix an issue and I can then set rest of the values with xpath.  

**xmlns="http://java.sun.com/xml/ns/javaee"**

Original: 

`<web-app xmlns="http://java.sun.com/xml/ns/javaee" metadata-complete="true" version="3.0" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`

Working: 
`<web-app metadata-complete="true" version="3.0" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`

I think this might be a bug. 

All the best. 

Stefan

**Comment by sm4rk0** [comment]
No, it's not a bug but a feature.
Please check the answers to #107, #112 and #117.

**Comment by dagwieers** [comment]
The xml module is upstream now. Please close this issue, and if needed, open a new issue at: https://github.com/ansible/ansible/issues
