### ISSUE TITLE
Relicense xml module as GPLv2 or later (including GPLv3)

### ISSUE THREAD

**Issue by dagwieers** [cmprescott/ansible-xml#113]
One of the issues holding us back to upstream this module (#52, ansible/ansible#25323), is the fact that it currently is strictly licensed as GPLv2-only while upstream modules need to be licensed as GPLv3.

So we need everyone that made contributions to the xml module to explicitly allow for relicensing their contributions to the xml module to GPLv2 or later. *The statement asks for "GPLv2 or later" because it includes GPLv3 and this way it does not take away any rights you may have had on GPLv2 going forward.*

https://www.gnu.org/licenses/license-compatibility.en.html

Can everyone who contributed clearly express their agreement to change their contributions to GPLv3 ?

> I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public License, version 2 or later, including GPLv3.

**PLEASE ACT NOW!**

- ~@magnus919  --  *copyright on file only*~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-307360379
- ~@h0nIg  --  [contributions](https://github.com/cmprescott/ansible-xml/commits/master/library/xml?author=h0nIg)~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-306260052
- ~@cmprescott  --  [contributions](https://github.com/cmprescott/ansible-xml/commits/master/library/xml?author=cmprescott)~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-315808284
- ~@cchepelov  --  [contributions](https://github.com/cmprescott/ansible-xml/commits/master/library/xml?author=cchepelov)~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-305826594
- ~@tbielawa  --  [contributions](https://github.com/cmprescott/ansible-xml/commits/master/library/xml?author=tbielawa)~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-305874860
- ~@relaxnow  --  [contributions](https://github.com/cmprescott/ansible-xml/commits/master/library/xml?author=relaxnow)~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-306813748
-  ~@quetzai  --  [contributions](https://github.com/cmprescott/ansible-xml/commits/master/library/xml?author=quetzai)~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-306526772
- ~@drkn  --  [contributions](https://github.com/cmprescott/ansible-xml/commits/master/library/xml?author=drkn)~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-315905809
- ~@puzan  --  [contributions](https://github.com/cmprescott/ansible-xml/commits/master/library/xml?author=puzan)~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-305957425
- ~@greaber  --  [contributions](https://github.com/cmprescott/ansible-xml/commits/master/library/xml?author=greaber)~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-305853742
- ~@dekimsey  --  [contributions](https://github.com/cmprescott/ansible-xml/commits/master/library/xml?author=dekimsey)~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-305865569
- ~@dagwieers  --  [contributions](https://github.com/cmprescott/ansible-xml/commits/master/library/xml?author=dagwieers)~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-305823900
- ~@beeme1mr  --  [contributions](https://github.com/cmprescott/ansible-xml/commits/master/library/xml?author=beeme1mr)~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-305908386
- ~@agx  --  [contributions](https://github.com/cmprescott/ansible-xml/commits/master/library/xml?author=agx)~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-305837171
- ~@martinboy  --  [contributions](https://github.com/cmprescott/ansible-xml/commits/master/library/xml?author=martinboy)~  --  https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-316287186

Relates to: #73 and #86

**Comment by dagwieers** [comment]
I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public Licence, version 2 or later.

**Comment by cchepelov** [comment]
Hi Dag,

thanks for carrying this!

Of course, I hereby grant permission to license my contributions to the 
ansible-xml module under the GNU General Public Licence, version 2 or later.
||
||

|-- Cyrille |

**Comment by agx** [comment]
I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public License, version 2 or later, including GPLv3.

**Comment by greaber** [comment]
I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public License, version 2 or later, including GPLv3.

**Comment by dekimsey** [comment]
I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public License, version 2 or later, including GPLv3.

**Comment by tbielawa** [comment]
I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public Licence, version 2 or later, including GPLv3.

**Comment by beeme1mr** [comment]
I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public License, version 2 or later, including GPLv3.

**Comment by puzan** [comment]
I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public License, version 2 or later, including GPLv3.

**Comment by h0nIg** [comment]
I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public Licence, version 2 or later, including GPLv3.

**Comment by dagwieers** [comment]
One friendly nudge to @magnus919 @h0nIg @cmprescott@relaxnow @quetzai @drkn @martinboy 
Please respond with no delay whether you agree to relicense your contributions to the Ansible xml module.

**Comment by quetzai** [comment]
Hi, sorry for the delay,
I hereby grant permission to license my contributions to the ansible-xml
module under the GNU General Public License, version 2 or later, including
GPLv3.

On Jun 2, 2017 11:47, "Cyrille Chépélov" <notifications@github.com> wrote:

Hi Dag,

thanks for carrying this!

Of course, I hereby grant permission to license my contributions to the
ansible-xml module under the GNU General Public Licence, version 2 or later.
||
||

|-- Cyrille |

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cmprescott/ansible-xml/issues/113#issuecomment-305826594>,
or mute the thread

**Comment by dagwieers** [comment]
We are *very* close to upstreaming this module, we only need 5 more people (out of 15)  to approve this.

Friendly reminder to: @magnus919 @cmprescott @relaxnow @drkn @martinboy
Please respond ASAP whether you agree to relicense your contributions to ansible-xml as GPLv2+.

Everything else is prepared, CI environment, integration tests, required cleanup, ...

**Comment by relaxnow** [comment]
I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public License, version 2 or later, including GPLv3.

**Comment by magnus919** [comment]
I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public License, version 2 or later, including GPLv3.

**Comment by dagwieers** [comment]
We are still *very close* to upstreaming this module, we only need 3 more people (out of 15)  to approve this.

Friendly reminder to: @cmprescott @drkn @martinboy
Please, please, please respond ASAP whether you agree to relicense your contributions to ansible-xml as GPLv2+.

Everything else is prepared, CI environment, integration tests, required cleanup, ... https://github.com/ansible/ansible/pull/25323 So we are really only waiting for you.

**Comment by dagwieers** [comment]
We are now close to 3 weeks into this relicensing dance, and we are still waiting for @cmprescott @drkn and @martinboy to respond on whether they agree to relicense their contributions to ansible-xml as GPLv2+.

**Please answer your personal email from me, or reply in this Github issue ticket.**

PS @cmprescott without your support there's little hope for closing existing tickets and moving things over to upstream.

**Comment by ksylvan** [comment]
Repeating the above plea. This module is super useful and should be in upstream.

Friendly reminder to: @cmprescott @drkn @martinboy
Please, please, please respond ASAP.

**Comment by dagwieers** [comment]
We are still waiting for feedback from @cmprescott @drkn @martinboy 

45 days and counting...
*Please respond ASAP !*

**Comment by ksylvan** [comment]
I left @cmprescott a message here: http://chrisprescott.beer/about/#comment-3077

**Comment by cmprescott** [comment]
I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public License, version 2 or later, including GPLv3.

**Comment by drkn** [comment]
I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public License, version 2 or later, including GPLv3.

**Comment by ksylvan** [comment]
Okay, now if @martinboy can do it, we are good to go! 👍

**Comment by martinboy** [comment]
I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public License, version 2 or later, including GPLv3.

**Comment by dagwieers** [comment]
We can still make Ansible v2.4.
Thanks everybody !

**Comment by ksylvan** [comment]
Awesome!

**Comment by dagwieers** [comment]
The module has been merged upstream so it will ship in v2.4. Thanks everybody !

Next up: (1) going over all open issues and closing/fixing them, and (2) adding backup/diff support.

PS I am still looking for people interested in helping maintain the xml module going forward. If you depend on this module and you are willing to help answer issues and PRs, and improving this module, speak up now ! The more maintainers we can add, the less work it will be for all. Thanks !

**Comment by tbielawa** [comment]
This is awesome!
