### ISSUE TITLE
Feature idea: Add 'namespace catch' in issue_template.md

### ISSUE THREAD

**Issue by sm4rk0** [cmprescott/ansible-xml#118]
A lot of issues are being open due to lack of documentation and due to missing namespaces argument. A note within the issue template about how the namespaces should be handled would help both the users and contributors until the module is upstreamed.
https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by sm4rk0** [comment]
So far, I identified these issues caused by this misunderstanding: #102, #107, #112 and #117.

**Comment by dagwieers** [comment]
I like it, but if we are moving this Ansible module upstream, this point is moot.
It would help if the documentation regarding namespaces is more clear.

The upstream module has examples and a note added to the documentation.

**Comment by dagwieers** [comment]
The xml module is upstream now. Please close this issue, or open a new issue at: https://github.com/ansible/ansible/issues

**Comment by sm4rk0** [comment]
> The upstream module has examples and a note added to the documentation.

I agree. Except the examples (no namespace usage there). I'll make a PR with few examples with namespaces when I find some time.

**Comment by dagwieers** [comment]
@sm4rk0 You are right, I think they got lost when I started from the original code (and added the various commits) when upstreaming.

PS If you want to help with maintaining this module, I am looking for people that can help respond to issues, review PRs and help improve the module. Let me know if you're interested !

**Comment by dagwieers** [comment]
@sm4rk0 I add your task to a new community page: https://github.com/ansible/community/wiki/Module:-xml

This is an experiment to see if we can create small loose-tight communities around modules. Feel free to add other TODO items to that list.

**Comment by sm4rk0** [comment]
@dagwieers I'm in.
Regarding namespace examples: there are a lot of them in [tests](https://github.com/ansible/ansible/tree/devel/test/integration/targets/xml/tasks). Maybe that's why you thought they were added to docs. I'll pick few test cases as representative examples for docs.

**Comment by dagwieers** [comment]
@sm4rk0 You're a maintainer now ! Welcome :-)
