### ISSUE TITLE
winrm send_input failed

### ISSUE THREAD

**Issue by MiguelHigorre** [cmprescott/ansible-xml#121]
Environment
Ubuntu 14.04
ansible 2.3.2.0
python version 2.7.6
pywinrm (0.2.2)
Windows 2012 R2

yml example
xml:
        path: 'Path/to/file'
        xpath: /configuration/appSettings
        value: 'localhost:443

Expected
XML file should be updated

Actual
[WARNING]: FATAL ERROR DURING FILE TRANSFER: Traceback (most recent call last):   File
"/usr/lib/python2.7/dist-packages/ansible/plugins/connection/winrm.py", line 267, in _winrm_exec
self._winrm_send_input(self.protocol, self.shell_id, command_id, data, eof=is_last)   File
"/usr/lib/python2.7/dist-packages/ansible/plugins/connection/winrm.py", line 248, in
_winrm_send_input     protocol.send_message(xmltodict.unparse(rq))   File
"/usr/local/lib/python2.7/dist-packages/winrm/protocol.py", line 207, in send_message     return
self.transport.send_message(message)   File "/usr/local/lib/python2.7/dist-
packages/winrm/transport.py", line 202, in send_message     raise WinRMTransportError('http',
error_message) WinRMTransportError: (u'http', u'Bad HTTP response returned from server. Code
500')

**Comment by sm4rk0** [comment]
I'm not 100% sure, but this module isn't supposed to be run on a Windows machine.
@dagwieers or @cmprescott can you confirm?

Anyway, this module has been upstreamed to Ansible. It's currently in devel version, which should be released as 2.4.0 in [Mid-September](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_4.rst). As a consequence, all the issues should be reported to [ansible](https://github.com/ansible/ansible/issues).

**Comment by dagwieers** [comment]
There is an alternative **win_xml** module available at: https://github.com/ansible/ansible/pull/26404
