### ISSUE TITLE
comprescott.xm fails with centos user

### ISSUE THREAD

**Issue by emailashwini** [cmprescott/ansible-xml#126]
Hi,
I have included the comprescott.xml in my roles

The script runs successfully as a root user but when i try to execute as centos user it gives me
 ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/tmp/test.yml': line 10, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

Does it requires to be executed as only root user ? Can it work with any other user ?

Thanks,

**Comment by dagwieers** [comment]
This repository is not a role, but an **xml** module. This **xml** module is now upstream in Ansible v2.4.
If you need support with Ansible or the xml module, please use the Ansible forum or IRC channel.

https://www.ansible.com/community

PS If you want help with a playbook, it helps to include that playbook.
