### ISSUE TITLE
deliverable package

### ISSUE THREAD

**Issue by emailashwini** [cmprescott/ansible-xml#127]
I have ansible 2.3 and i was successful in installing but if i want to make this library available within a local repository having no internet connection. How can I achieve this ? is there a rpm deliverable available ?

Thanks,

**Comment by sm4rk0** [comment]
This is a module, not a library, although it's only one file (xml.py) that sits in a directory named library. You can get it by:
1. [installing](https://docs.ansible.com/ansible/latest/intro_installation.html) ansible v2.4 or higher (as it is now part of Ansible)
2. copying the [xml.py](https://github.com/cmprescott/ansible-xml/blob/master/library/xml.py) to the default Ansible library directory
3. copying it into a `library` subdirectory relative to playbook file(s). More info [here](https://docs.ansible.com/ansible/latest/intro_configuration.html#library).

@dagwieers do you know if [xml.py from ansible repo](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/xml.py) would work with v2.3?

**Comment by dagwieers** [comment]
@sm4rk0 Possibly, I don't remember if we do something that requires v2.4, and I can't remember what changed to the module interface in v2.4 either. Probably best to test.

**Comment by dagwieers** [comment]
I am closing this issue as we are approaching v2.5 and this module is upstream since v2.4.
