### ISSUE TITLE
Update "xml:base" attribute

### ISSUE THREAD

**Issue by tapvirvirk** [cmprescott/ansible-xml#128]
I have a xml containing xml:base attribute. I'm trying to update the attribute but ansible is failing.
Below is the short sample of the example.

`<?xml version='1.0' encoding='utf-8' ?>
<workbook xml:base='https://test.com'>
</workbook>`

**Comment by tapvirvirk** [comment]
Error is 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'xml'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_aFoMv2/ansible_module_xml.py\", line 853, in <module>\n    main()\n  File \"/tmp/ansible_aFoMv2/ansible_module_xml.py\", line 839, in main\n    set_target(module, doc, xpath, namespaces, attribute, value)\n  File \"/tmp/ansible_aFoMv2/ansible_module_xml.py\", line 573, in set_target\n    changed = set_target_inner(module, tree, xpath, namespaces, attribute, value)\n  File \"/tmp/ansible_aFoMv2/ansible_module_xml.py\", line 565, in set_target_inner\n    attribute = \"{{{0}}}{1}\".format(namespaces[attr_ns], attr_name)\nKeyError: 'xml'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

**Comment by tapvirvirk** [comment]
`- name: "Modify xml:base attribute"
  xml:
    path: /opt/tableau/output/test_2.twb
    xpath: /workbook
    attribute: "xml:base"
    pretty_print: yes
    value: 'http://localhost'`

**Comment by tapvirvirk** [comment]
I would really appreciate if you could help in resolving the issue

**Comment by dagwieers** [comment]
You have not specified what the "xml" namespace is about. Please look at the notes in the documentation: https://docs.ansible.com/ansible/2.5/modules/xml_module.html#notes especially related to namespaces.

Please re-open this issue at https://github.com/ansible/ansible if that error still is shown on Ansible v2.4 or Ansible v2.5.
