### ISSUE TITLE
"Xpath /settings/setting[@id="setting.key"]/@value does not reference a node!" when trying to set an attribute value

### ISSUE THREAD

**Issue by Lx** [cmprescott/ansible-xml#15]
Give this Ansible task:

``` yaml
- name: ensure required setting
  xml: >
    file=.../settings.xml
    xpath='/settings/setting[@id="setting.key"]/@value'
    value=true
```

and this remote XML file:

``` xml
<settings>
    <setting id="setting.key" value="false" />
</settings>
```

I get this error:

```
TASK: [playbook | ensure required setting] ******************* 
failed: [XXX] => {"failed": true}
msg: Xpath /settings/setting[@id="setting.key"]/@value does not reference a node!
```

The documentation (through showing how to remove an attribute) suggests that I should be able to alter an attribute's value.  Am I doing something wrong?

**Comment by codyro** [comment]
I'm also having the issue described above when trying to set a value for an attribute. After peaking at the code it doesn't seem to account for changing an attribute?

**Comment by add1ct3dd** [comment]
Any solutions to this?

**Comment by Hubbitus** [comment]
I also come here with intention fill bug...
But it seems we misunderstood (and doc has not useful description and examples). I have looked at code and it intended to work in other way (on my mind used in question much more sane and I also understand and try it on that manner). So in current implementation it works for me if I pass separate attribute value like:
```
- name: ensure required setting
  xml:
    file: .../settings.xml
    xpath: '/settings/setting[@id="setting.key"]'
    attribute: value
    value: "some new value"
```
Please note few thing there:
* xpath is always element
* attribute has name without @

**Comment by cmprescott** [comment]
I'll use this issue to track updating the documentation's clarity concerning this.

**Comment by dagwieers** [comment]
The xml module is upstream now (and ships with Ansible v2.4).

**Please close this issue**, and retest against the new upstream xml module. If needed, open a new issue at: https://github.com/ansible/ansible/issues

**Comment by dagwieers** [comment]
@Hubbitus Are you willing to create a PR for this at: https://github.com/ansible/ansible ?

I just verified the same thing. This does not work:
```yaml
[dag@moria ansible.git]$ ansible -m xml -a 'file=/tmp/test2.xml xpath=/settings/setting[@id="setting.key"]/@value value=true' localhost --diff --check
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Xpath /settings/setting[@id=\"setting.key\"]/@value does not reference a node! tree is <settings>\n    <setting id=\"setting.key\" value=\"\"/>\n</settings>\n"
}

[dag@moria ansible.git]$ ansible -m xml -a 'file=/tmp/test2.xml xpath=/settings/setting[@id="setting.key"]/@value attribute=value value=true' localhost --diff --check
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Xpath /settings/setting[@id=\"setting.key\"]/@value does not reference a node! tree is <settings>\n    <setting id=\"setting.key\" value=\"\"/>\n</settings>\n"
}
```

But this works fine:
```yaml
[dag@moria ansible.git]$ ansible -m xml -a 'file=/tmp/test2.xml xpath=/settings/setting[@id="setting.key"] attribute=value value=true' localhost --diff --check
--- before
+++ after
@@ -1,4 +1,4 @@
 <?xml version='1.0' encoding='UTF-8'?>
 <settings>
-    <setting id="setting.key" value="false"/>
+    <setting id="setting.key" value="true"/>
 </settings>

localhost | SUCCESS => {
    "actions": {
        "namespaces": {}, 
        "state": "present", 
        "xpath": "/settings/setting[@id=\"setting.key\"]"
    }, 
    "changed": true, 
    "failed": false, 
}
```

**Comment by dagwieers** [comment]
I have updated the documentation. Setting attribute values using xpath only would be very useful, but is a feature request. We are welcoming anyone who can do this.
