### ISSUE TITLE
No documentation on how to install this module.

### ISSUE THREAD

**Issue by yeroc** [cmprescott/ansible-xml#23]
It would be great to add a section to the README.md on how to install this module.  This may be obvious to experienced users of Ansible but not so much for more casual or new users...

**Comment by cmprescott** [comment]
That's a good idea. I figured out how to do it through http://docs.ansible.com/ansible/playbooks_roles.html#embedding-modules-in-roles . Is that clear enough for what you were thinking or were you thinking of specifically for this module?

**Comment by yeroc** [comment]
I ended up putting it in the top-level `library` directory (which likely makes the most sense for users that would typically use this in multiple roles) following the [best-practices layout](http://docs.ansible.com/ansible/playbooks_best_practices.html#directory-layout) but it took me some googling to get there as I didn't realize that module installation was documented there, and even that isn't very clear.

There should be an Installation section in the README that outlines:
```
# in your top-level play directory...
mkdir library
cd library
# for current dev code...
git clone https://github.com/cmprescott/ansible-xml.git
# or grab release .zip file...
wget https://github.com/cmprescott/ansible-xml/archive/0.3.0.zip /tmp
unzip /tmp/0.3.0.zip
```
The above is un-tested but that ought to be the general sketch I'd think?

**Comment by cmprescott** [comment]
At first, I did the same you did. However, I ran into problems with getting the module working with `library/ansible-xml/library`. They may have corrected module scanning issues since I tried that. 

The way I use modules is I place them in the `roles` directory.
```bash
# in your top-level play directory...
cd roles
# retrieve the module from GitHub...
git clone https://github.com/cmprescott/ansible-xml.git
```yaml
  roles: 
    # include xml module first!
    - ansible-xml
    # then include roles that use ansible-xml
```yaml

```

**Comment by yeroc** [comment]
I can confirm the above worked with `ansible 1.9.1`.  I didn't get very far with using this module though as I couldn't figure out how to do some fairly straightforward manipulations so ended up taking a different approach.

**Comment by Jonnymcc** [comment]
Consider uploading this to Ansible Galaxy and letting it be installed with the ansible-galaxy tool? We put our custom modules in ansible/playbooks/library, no need to include the module as a role.

**Comment by situokko** [comment]
Same issue for me, this was the first 3rd party module I use. It took me quite I while to figure out how it is installed.

Please add both of these ways to README. Thank you!

**Comment by tbielawa** [comment]
At the very least, we should link to official upstream documentation, if it
exists
