### ISSUE TITLE
Module parameters are missing on target host

### ISSUE THREAD

**Issue by peterschen** [cmprescott/ansible-xml#24]
This is my task:

```
- name: Remove default H2 configuration (1/2)
  xml: xpath=/server/profile/subsystem/datasources/datasource[@pool-name=ExampleDS] file=/opt/apps/jboss/standalone/configuration/standalone.xml ensure=absent
```

This is what ansible executes on the target:

<pre>ansible-xml: Invoked with xpath= count=None set_children=None namespaces={} attribute=None pretty_print=False add_children=None value=None ensure=absent file=/opt/apps/jboss/standalone/configuration/standalone.xml print_match=None xmlstring=None</pre>

Note that `xpath` is missing so the call is pretty useless.

**Comment by cmprescott** [comment]
I believe the **-** in `/server/profile/subsystem/datasources/datasource[@pool-name=ExampleDS]` needs to be escaped. See http://stackoverflow.com/questions/11301650/how-to-escape-indicator-characters-i-e-or-in-yaml

**Comment by peterschen** [comment]
Thanks for your answer. It's just a display problem of ansible. Due to the equal sign the whole parameter is not logged to the syslog. I was suspecting that the whole module was not executed but I was able to narrow that down to problems with the XML namespaces.
