### ISSUE TITLE
Add xml module in Ansible-Galaxy

### ISSUE THREAD

**Issue by bamartos** [cmprescott/ansible-xml#26]
Hi,

I know that is not really an issue, mostly a future request. Is there any plan of adding the xml module in the Ansible Galaxy? 

Thank you for this nice module,

Cheers,

Vasilis

**Comment by cmprescott** [comment]
After resolving the latest triage of bugs, I'll prep the role for the Ansible Galaxy. There seems to be multiple sporadic requests for this. Thanks for creating the issue.
