### ISSUE TITLE
function request: ensure element present (only add when it does not already exist)

### ISSUE THREAD

**Issue by sgiebels** [cmprescott/ansible-xml#35]
I've been trying to edit xfce4-keyboard-shortcuts.xml to add some shortcut keys, but I've translated my question/problem back to the 'ansible-xml-beers.xml' examples you have provided with ansible-xml to ease the discussion.

original ansible-xml-beers.xml:
```
<?xml version='1.0' encoding='UTF-8'?>
<business type="bar">
  <name>Tasty Beverage Co.</name>
  <beers>
    <beer>Rochefort 10</beer>
    <beer>St. Bernardus Abbot 12</beer>
    <beer>Schlitz</beer>
  </beers>
  <rating subjective="true">10</rating>
  <website>
    <mobilefriendly/>
    <address>http://tastybeverageco.com</address>
  </website>
```
I want to add a beer next to the existing beer elements in the <beers> node, e.g.:  `<beer>Heineken</beer>`, but only if it is not already present.

I've tried "test-add-children-elements.yml", but this will add this beer-element every time the Ansible Playbook runs.
After running "test-set-children-elements.yml", as expected, only the beer element I've selected is in the <beers> node while all other previously present beer elements in the xml file are removed.

Is there a  (single) function similar to "test-add-children-elements.yml", which will ensure that the specified child element will be present (with specified attributes), add it if it does not exist but leave the other existing <beer> elements in place? Additionally, doing this in such a way if an element like `<beer type="Dutch">Heineken</beer>` exists and I want to change it to `<beer type="European">Heineken</beer>`, no duplicates will be created?

**Comment by cmprescott** [comment]
Hey, sorry taking so long to take a look at this.

What version did you try this with? I think I addressed this issue in https://github.com/cmprescott/ansible-xml/commit/b17360059ec338ed4e53a4336ff7415d2a1bfde2

It's in the current master. Do you mind updating and trying again?

**Comment by neingeist** [comment]
I have the same issue using `add_children`. Test case is here:

https://github.com/neingeist/ansible-xml/commit/e4216277d25f5c4f16c4b405505e3f50e4d72ba8

**Comment by cmprescott** [comment]
My thoughts in https://github.com/cmprescott/ansible-xml/issues/42
