### ISSUE TITLE
Xpath  does not reference a node!

### ISSUE THREAD

**Issue by psi-4ward** [cmprescott/ansible-xml#37]
config.xml

``` xml
<?xml version='1.0' encoding='UTF-8'?>
<hudson></hudson>
```

Task

``` yaml
  xml:
    file="/var/lib/jenkins/config.xml"
    xpath="/hudson/blaaa"
    value="pete"
```

Error:

```
msg: Xpath /hudson/blaaa does not reference a node!
```

I would expect a new Node `<blaaa>pete</blaaa>` would be generated.

**Comment by psi-4ward** [comment]
The problem does NOT exist with v.0.3.0

**Comment by hudecof** [comment]
The same with verzion 0.3.1 when tryiing to add property

failed: [xxx.uuu.zzz] => {"failed": true}
msg: Xpath /Server/Service/Connector/@proxyName does not reference a node!

**Comment by hudecof** [comment]
Tho sone works, but there is no word about attribute keyword. Needed to read the source.

  xml:
    file: conf/server.xml"
    xpath: /Server/Service/Connector
    attribute: proxyNName
    ensure: present
    value: xxx.uuu.zzz

**Comment by slavafomin** [comment]
Thanks @hudecof you've saved my day!

**Comment by ssbarnea** [comment]
Interestengly, I reached the same bug. I was expecting that spacifying a xpath and `ensure: present` will create this path inside the xml document. Instead, I get the same error. 

I don't need to do anything related to `attribute`, so I don't really see why to use them.
