### ISSUE TITLE
function request : add comment, or comment a block.

### ISSUE THREAD

**Issue by simonpie** [cmprescott/ansible-xml#40]
It would be very useful to be able to add a child comment to xml or to be able to comment a full element as xml :
For example adding
`<!--URL Pattern to skip the XSS prevention-->`
or commenting an existing child :
`<Pattern>wso2</Pattern>`
becomes
`<!--Pattern>wso2</Pattern-->`

**Comment by dagwieers** [comment]
The xml module is upstream now (and ships with Ansible v2.4).

**Please close this issue**, and retest against the new upstream xml module. If needed, open a new issue at: https://github.com/ansible/ansible/issues

**Comment by dagwieers** [comment]
This issue was moved to ansible/ansible#28195
