### ISSUE TITLE
Strip/encoding tags issue

### ISSUE THREAD

**Issue by avra911** [cmprescott/ansible-xml#41]
Hi,

While trying to save the value with `value="<![CDATA[{{ mysql_db_password }}]]>"`, the module is encoding the tags with `&lt;![CDATA[...]]&gt;`.

Is there any way to allow such tags?

Thanks,
Razvan

**Comment by cmprescott** [comment]
If you're feeling ambitious, you can test out modifying the code `etree.XMLParser(strip_cdata=False)` form http://lxml.de/api.html#cdata

**Comment by MedicMomcilo** [comment]
Can we add feature request here to add ansible option for striping cdata?

This was a big surprise to have ansible change file when no changes were necessary.

**Comment by dagwieers** [comment]
The xml module is upstream now (and ships with Ansible v2.4).

**Please close this issue**, and retest against the new upstream xml module. If needed, open a new issue at: https://github.com/ansible/ansible/issues
