### ISSUE TITLE
ERROR! 'version' is not a valid attribute for a RoleMetadata

### ISSUE THREAD

**Issue by slavafomin** [cmprescott/ansible-xml#44]
Hello!

Thank you for this great module!

However, I'm trying to use it with `ansible 2.0.0.2` and getting the following error:

```
ERROR! 'version' is not a valid attribute for a RoleMetadata

The error appears to have been in '/etc/ansible/roles/cmprescott.xml/meta/main.yml': line 2, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
galaxy_info:
^ here
```

Looks like metadata file has incorrect structure according to the latest Ansible requirements.

I've removed `version` field from the `/etc/ansible/roles/cmprescott.xml/meta/main.yml` file on my local machine and it helped.

Could you please fix this in the repo? Thank you!

Cheers!

**Comment by cmprescott** [comment]
This is my top priority as it blocks CI from checking PRs. 

Hopefully less than 24 hour turnaround. Thank you for reporting!
