### ISSUE TITLE
Question-Add a node 

### ISSUE THREAD

**Issue by danoyoung** [cmprescott/ansible-xml#48]
I'm new to parsing XML, so I may have my terms conflated and not know what the hell I'm talking about.... But I have a xml file like this:
```xml
<configuration>
 <property>
    <name>foo1</name>
    <value>bar</value>
  </property>
</configuration>
```
and I want to add a node, under the <configuration> parent, so I'll end up having:
```xml
<configuration>
 <property>
    <name>foo1</name>
    <value>bar</value>
  </property>

 <property>
    <name>foo1</name>
    <value>baz</value>
  </property>
</configuration>
```
Is that possible with this library?  and if so, any pointers/examples would be greatly `appreciated.`

**Comment by cmprescott** [comment]
See the unit test for adding children https://github.com/cmprescott/ansible-xml/blob/master/tests/test-add-children-elements.yml 
See xpath selecting nth item http://stackoverflow.com/a/4008925/618580

Playing with the unit tests is probably the easiest/quickest way to determine how you can accomplish your use case.
