### ISSUE TITLE
Get ansible-xml part of ansible core

### ISSUE THREAD

**Issue by ssbarnea** [cmprescott/ansible-xml#52]
XML Module should become part of Ansible core as that's really something belonging to core. Lets use this ticket to track the progress on getting it part of Ansible core.

**Comment by tbielawa** [comment]
:thumbsup:

**Comment by ssbarnea** [comment]
Here is the Feature request made on Ansible https://github.com/ansible/ansible/issues/16147 -- add your feedback and/or up-thumbs there.

**Comment by tbielawa** [comment]
*nudge*

**Comment by cmprescott** [comment]
@tbielawa thanks! Works been crazy lately, but I'll try to make time for this. It's long long overdue. I don't want to answer questions how to install it forever...

**Comment by cmprescott** [comment]
https://github.com/ansible/ansible-modules-core/pull/4122

**Comment by liquidat** [comment]
Any news on this? I would like to help with the submission of the module upstream. Or if you do not want to pursue that anymore, I would like to for it here on Github and push it upstream, if you would be ok with it.

**Comment by ssbarnea** [comment]
I do see this as a meta-ticket, there are quite a few bugs that do need to be fixed in order to do this. 

I think it would be wise if we specify them here in order to see what blocks this ticket, it would be much easier to move things into the right direction.

**Comment by dagwieers** [comment]
TBH I think we should get this merged ASAP in Ansible Core now that v2.3 has been branched. And then work on having integration tests, additional documentation and closing the existing PRs upstream to get this finished for v2.4 (which gives us 4 to 5 months probably).

**Comment by ssbarnea** [comment]
I don't need this anymore for my job but I will help with getting the PR reviewed and merged by Ansible team. Indeed timing is essential here, we don't want to lose that window.

BTW, I hope there are no licensing issues, as these to have the bad habit of ruining things.

**Comment by liquidat** [comment]
Are there any possible license issues you have on your mind?Am 16.03.2017 1:30 nachm. schrieb Sorin Sbarnea <notifications@github.com>:I don't need this anymore for my job but I will help with getting the PR reviewed and merged by Ansible team. Indeed timing is essential here, we don't want to lose that window.
BTW, I hope there are no licensing issues, as these to have the bad habit of ruining things.

**Comment by ksylvan** [comment]
Any news on this?

**Comment by dagwieers** [comment]
Can we get #108 and #109 merged ?

And speed up the upstreaming effort so that we can get wider testing *and* can add automated integration tests to test correctness.

I don't mind upstreaming it myself if resources are scarce... Feedback please.

**Comment by ksylvan** [comment]
Looks like this is proceeding nicely. This is the latest work, correct? https://github.com/ansible/ansible/pull/25323

**Comment by dagwieers** [comment]
Yes. So we prefer not to have any new PRs on this repository before this is merged.
Once merged I would like to move all feature requests and (valid) bug reports to the ansible/ansible repository. This will take some time to validate and possible fix the reported issues.

Still looking for people willing to help maintain the xml module upstream.

**Comment by dagwieers** [comment]
The xml module is upstream now (and ships with Ansible v2.4).

Anyone interested in helping to maintain this module upstream is welcome. We need a few people in order to be able to work independently on this module (with the existing review-process you need 2 shipits from maintainers to get stuff merged). Ideally we have about 5 to 6 people maintaining it. So please speak up !

**Please close this issue**.
