### ISSUE TITLE
Change values are failing , no error message, just not executed

### ISSUE THREAD

**Issue by xenexis** [cmprescott/ansible-xml#53]
Hi all,

I was trying to use like : 

../role/artifactory/defaults/main.yml has contain:

> artifactory_proxy:

```
- key: "test-proxy"
- host: "192.168.1.1"
- port: "3128"
- username: ""
- password: ""
- defaultProxy: "false" 
```

and the ../role/artifactory/task/configure.yml 
- name:  Artifactory config | Add proxy settings to the config
  xml:
    file: /tmp/artifactory.config.xml
    xpath: /config/proxies/proxy
    add_children: "{{ artifactory_proxy }}"

The task finished with ok, but there is no change, and if the proxy element is not exist in the xml file it fail with a strange ssh error ...
What I do wrong ?

Thanks!

**Comment by ksylvan** [comment]
I think I am seeing something very similar to this, trying to add a child `<profile>` to the `<profiles>` section of a Maven `settings.xml` file.

**Comment by ITler** [comment]
Explicitly use namespaces to get this working:
    
    xml:
      file: ...
      namespaces:
        set: http://maven.apache.org/SETTINGS/1.0.0
      xpath: /set:settings/set:profiles
      add_children:
        ...

**Comment by dagwieers** [comment]
The xml module is upstream now (and ships with Ansible v2.4).

**Please close this issue**, and retest against the new upstream xml module. If needed, open a new issue at: https://github.com/ansible/ansible/issues

**Comment by dagwieers** [comment]
Since this seems to be related to namespace-issues, I am going to close this issue. Feel free to reopen upstream.
