### ISSUE TITLE
unable to create node, noop

### ISSUE THREAD

**Issue by dekimsey** [cmprescott/ansible-xml#7]
> Add a validxhtml element to the website element. Note that ensure is present by default, and value
> defaults to null for elements. The result is something like <website><validxhtml />...</website>
> 
> ```
> xml: file=/foo/bar.xml xpath=/business/website/validxhtml
> ```

The example in the readme does not seem to work. The module fails without output. I've looked through the test cases and haven't found this case. I don't believe the autovivification behaivor is working as intended.

I had to hack in RHEL5/Python 2.4 support, so it is possible that is an issue. There is a branch that shows the fix for that.

**Comment by markkasun** [comment]
Is there a work around to add a node if it does not exist but do nothing if it already exists?

**Comment by mputilin** [comment]
having the same issue. any fixes?

**Comment by cmprescott** [comment]
I'll use this as the issue to track adding documentation to clear this up. Also see issues https://github.com/cmprescott/ansible-xml/issues/42 & https://github.com/cmprescott/ansible-xml/issues/35

**Comment by dagwieers** [comment]
The xml module is upstream now (and ships with Ansible v2.4).

**Please close this issue**, and retest against the new upstream xml module. If needed, open a new issue at: https://github.com/ansible/ansible/issues

**Comment by dagwieers** [comment]
This is working fine for me with the upstreamed version in Ansible v2.4:
```yaml
[dag@moria ansible.git]$ ansible -m xml -C --diff -a 'xpath=/business/website/validxhtml file=/tmp/test3.xml' localhost
--- before
+++ after
@@ -1,4 +1,4 @@
 <?xml version='1.0' encoding='UTF-8'?>
 <business>
-  <website/>
+  <website><validxhtml/></website>
 </business>

localhost | SUCCESS => {
    "actions": {
        "namespaces": {}, 
        "state": "present", 
        "xpath": "/business/website/validxhtml"
    }, 
    "changed": true, 
    "failed": false, 
}
```

**Comment by dagwieers** [comment]
So I am going to close this issue, let us now if you have any (new) issues at: https://github.com/ansible/ansible/issues
