### ISSUE TITLE
Dict elements not supported on add_children

### ISSUE THREAD

**Issue by tonydoval** [cmprescott/ansible-xml#72]
Hello,

Dict elements not supported on add_children

With a task like:
  - name: Create environment
    xml:
      namespaces:
        reports: http://xmlns.oracle.com/reports/server
      file: '{{ rwserver_conf }}'
      xpath: /reports:server
      pretty_print: true
      add_children: 
        - environment:
            id: '{{ item.value.nombre }}'
      with_dict: '{{ entornos }}'

Variable:
entornos:
    libra:
      { nombre: 'test1' }
    pruebas:
      { nombre: 'test2' }

I got message:
fatal: [192.168.231.178]: FAILED! => {"failed": true, "msg": "'item' is undefined"}

Is it possible to create multiple child elements with a dictionary variable?

Thanks in advance

**Comment by cmprescott** [comment]
released in 0.3.4
