### ISSUE TITLE
Update from GPLv2 to GPLv3

### ISSUE THREAD

**Issue by cmprescott** [cmprescott/ansible-xml#73]
See https://github.com/ansible/ansible-modules-core/pull/4122#discussion_r69841038

From my understanding the project needs permission from original maintainers ( @tbielawa & @github_rhinception ) to change the license. 

@tbielawa do you grant permission or know how I can ping to get permission?

**Comment by macdiesel** [comment]
@cmprescott Looks like there is a response in #86 from Tim about updating the license.

**Comment by dagwieers** [comment]
Re-license is done. This can be closed.

**Comment by macdiesel** [comment]
Thank you all!
