### ISSUE TITLE
Doesn't work with Oracle WebLogic config.xml

### ISSUE THREAD

**Issue by bdgscotland** [cmprescott/ansible-xml#83]
Seems to say that Xpath does not reference a node.
Doesn't seem to be able to handle the lengthy <domain> opening tag.

**Comment by fogartyp** [comment]
Was able to parse to view values using this play.

This was 11g using Ansible 2.2
---
- hosts: all
  tasks:
    - name: Print Domain Name
      xml:
        file: "{{ weblogic_domain_path }}/config/config.xml"
        namespaces:
          dom: http://xmlns.oracle.com/weblogic/domain
        xpath: "/dom:domain/dom:name"
        content: 'text'

**Comment by dagwieers** [comment]
The xml module is upstream now (and ships with Ansible v2.4).

**Please close this issue**, and if needed, open a new issue at: https://github.com/ansible/ansible/issues

**Comment by dagwieers** [comment]
Right so, this seems to be yet another namespace-related issue. So it's important in XML to namespace everything that requires it.
