### ISSUE TITLE
Make xml idempotent

### ISSUE THREAD

**Issue by dagwieers** [cmprescott/ansible-xml#91]
Currently when you use set_children with the exact elements that were in place before (i.e. the content of the file was not changed) the xml module does report a change. So that's obviously wrong.

On top of that, I would expect the xml module to verify the content (and not formatting) with the previous version to establish it being changed. Currently it does not even do that.

BTW I will have to reproduce my findings with JBoss configuration wrangling.

**Comment by juju4** [comment]
As a temporary workaround, you can use xmllint to check value
https://github.com/juju4/ansible-jenkins/blob/master/tasks/jenkins-ssh-auth.xml

**Comment by gitmlynch** [comment]
This module is working really nicely for me for some jenkins configuration,(appreciation to @cmprescott), but the idempotency issue is a real bummer.

**Comment by dagwieers** [comment]
I think I nailed this bug now when upstreaming the xml module. If this would still be an issue to someone, please open a new issue at: https://github.com/ansible/ansible
