### ISSUE TITLE
Support of loops ?

### ISSUE THREAD

**Issue by dawez** [cmprescott/ansible-xml#93]
Are loops supported ? For example I am trying to change the same attribute in multiple files. This example below is working when I process one file per time

```
- name: testing loop
  debug: msg="{{ item }}"
  with_items:
    - "{{ file1 }}"
    - "{{ file2 }}"
    - "{{ file3 }}"

# todo there should be a loop here
- name: trying to replace in a loop
  xml:
    file: "{{ item }}"
    xpath: "{{ mycustomxpath }}"
    attribute: value
    value: "mycustom value"
    with_items:
      - "{{ file1 }}"
      - "{{ file2 }}"
      - "{{ file3 }}"
      
```
Then I have this error appearing:
```
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined\n\nThe error appears to have been in '/home/user/work/project/ops/roles/deploy/tasks/upload_code.yml': line 32, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# todo there should be a loop here\n- name: trying to replace in a loop\n  ^ here\n"
}
```

**Comment by dagwieers** [comment]
Yes, I would be interested in the same functionality. So a single task could be used for modifying multiple configuration items in an XML configuration file.

**Comment by rasputnik** [comment]
Don't you just need to fix your YAML?

with_items should be nested as deeply as the file: task, not as deep as its arguments.

**Comment by dagwieers** [comment]
It appears a problem with the example and not an actual bug. Please close this issue.

In case you do find a problem with the xml module, please try the upstream xml module (in Ansible v2.4) and if needed, open an issue at: https://github.com/ansible/ansible/issues
