### ISSUE TITLE
Question: Can you create a node with a value and children?

### ISSUE THREAD

**Issue by Chris-YBS** [cmprescott/ansible-xml#99]
For example:

\<enclosing\>
  \<newNode att="one"\>two\</newNode\>
\</enclosing\>
\</code\>
I can't see how to do this apart from creating a node and adding attributes seperately

**Comment by juju4** [comment]
In my own recent experience, create an empty node+attribute, and after children inside like
https://github.com/juju4/ansible-jenkins/blob/master/tasks/jenkins-ssh-auth.xml

**Comment by dagwieers** [comment]
@Chris-YBS There are 2 examples in #101, one using YAML syntax, the other using XML syntax.

**Comment by Chris-YBS** [comment]
Thanks @dagwieers
